### ISSUE TITLE
IllegalArgumentException after reloading classes.

### ISSUE THREAD

**Issue by vkolotov** [feliperazeek/playframework-elasticsearch#36]
After "hot reloading" classes of play application (e.g. changing source code while application is running) elasticsearch fails.
It happens when you just want to make a simple query. BUT, if you run application/test without code changes (even several times one after another), elastic search works well.

java.lang.IllegalArgumentException: Can not set java.util.List field models.Article.editions to models.Article
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:146)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:150)
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:37)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:18)
    at java.lang.reflect.Field.get(Field.java:358)
    at play.modules.elasticsearch.util.ReflectionUtil.getFieldValue(ReflectionUtil.java:115)
    at play.modules.elasticsearch.mapping.impl.CollectionFieldMapper.addToDocument(CollectionFieldMapper.java:77)
    at play.modules.elasticsearch.mapping.impl.PlayModelMapper.addModel(PlayModelMapper.java:130)
    at play.modules.elasticsearch.mapping.impl.PlayModelMapper.addModel(PlayModelMapper.java:26)
    at play.modules.elasticsearch.adapter.ElasticSearchAdapter.indexModel(ElasticSearchAdapter.java:147)
    at play.modules.elasticsearch.ElasticSearchIndexAction.invoke(ElasticSearchIndexAction.java:53)
    at play.modules.elasticsearch.ElasticSearchIndexer.doJob(ElasticSearchIndexer.java:54)
    at play.jobs.Job.doJobWithResult(Job.java:50)
    at play.jobs.Job.call(Job.java:146)
    at play.jobs.Job$1.call(Job.java:66)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

**Comment by bgooren** [comment]
Aha! thanks for pointing this out.
We hit this sometimes as well and I was wondering what caused it since it doesn't show up while unit testing.

**Comment by bgooren** [comment]
I think the reason for this is simply because two different classloaders/classes are involved (one for the old version of the class, one for the new version).
This explains why quite often in the play code classes are referred to by name instead of by getClass().equals(class).

**Comment by bgooren** [comment]
Fixed. We had a class cache somewhere which was not emptied on hot reload.
