### ISSUE TITLE
elasticsearch.local=true not working

### ISSUE THREAD

**Issue by yoko-** [feliperazeek/playframework-elasticsearch#5]
I just re-upgraded to 0.0.4 only to find that elasticsearch.local=true is still having issues. The ES version that works for me is 0.0.2. 
# application.conf

module.elasticsearch=${play.path}/modules/elasticsearch-0.0.4
elasticsearch.local=true
elasticsearch.client=false
# Stack Trace:

01:26:45,152 INFO  ~ Connecting Play! to Elastic Search in Client Mode
01:26:46,276 ERROR ~ 

@6601997gg
Internal Server Error (500) for request GET /

Oops: RuntimeException
An unexpected error occured caused by exception RuntimeException: Invalid Host: false

play.exceptions.UnexpectedException: Unexpected Error
    at play.Play.start(Play.java:458)
    at play.Play.detectChanges(Play.java:530)
    at play.Invoker$Invocation.init(Invoker.java:100)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: Invalid Host: false
    at play.modules.elasticsearch.ElasticSearchPlugin.onApplicationStart(ElasticSearchPlugin.java:105)
    at play.Play.start(Play.java:427)
    ... 3 more

**Comment by feliperazeek** [comment]
The documentation on 0.0.4 only has two options:

Option 1) 
Elastic Search (Local Model) elasticsearch.local=true

Option 2) 
Elastic Search (Client Model) elasticsearch.local=false elasticsearch.client=mynode1:9200,mynode2:9200

But I added some defensive code for the next release if local is true to ignore the client option.

**Comment by yoko-** [comment]
Felipe,

I have changed the conf file to:

#application.conf
module.elasticsearch=${play.path}/modules/elasticsearch-0.0.4
elasticsearch.local=true

# 

<b>But it is still not connecting in local mode:</b>

#Stack Trace
10:59:03,208 INFO  ~ Module elasticsearch is available (/Test/Play/play-1.1.1/modules/elasticsearch-0.0.4)
10:59:04,093 WARN  ~ You're running Play! in DEV mode
10:59:04,455 INFO  ~ Listening for HTTP on port 9000 (Waiting a first request to start) ...
10:59:23,380 WARN  ~ The path for a staticDir route must end with / (GET /public -> staticDir:public)
10:59:23,916 INFO  ~ Connecting Play! to Elastic Search in Client Mode
10:59:25,429 ERROR ~ 

@66046e46m
Internal Server Error (500) for request GET /

Oops: RuntimeException
An unexpected error occured caused by exception RuntimeException: Configuration required - elasticsearch.client when local model is disabled!

play.exceptions.UnexpectedException: Unexpected Error
    at play.Play.start(Play.java:458)
    at play.Play.detectChanges(Play.java:530)
    at play.Invoker$Invocation.init(Invoker.java:100)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: Configuration required - elasticsearch.client when local model is disabled!
    at play.modules.elasticsearch.ElasticSearchPlugin.onApplicationStart(ElasticSearchPlugin.java:98)
    at play.Play.start(Play.java:427)
    ... 3 more
13:31:12,675 INFO  ~ Connecting Play! to Elastic Search in Client Mode
13:31:12,852 ERROR ~ 

@66046e46n
Internal Server Error (500) for request GET /

Oops: RuntimeException
An unexpected error occured caused by exception RuntimeException: Configuration required - elasticsearch.client when local model is disabled!

play.exceptions.UnexpectedException: Unexpected Error
    at play.Play.start(Play.java:458)
    at play.Play.detectChanges(Play.java:530)
    at play.Invoker$Invocation.init(Invoker.java:100)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: Configuration required - elasticsearch.client when local model is disabled!
    at play.modules.elasticsearch.ElasticSearchPlugin.onApplicationStart(ElasticSearchPlugin.java:98)
    at play.Play.start(Play.java:427)
    ... 3 more

**Comment by feliperazeek** [comment]
http://geeks.aretotally.in/play-elastic-search-module-new-0-0-5-release-with-screencast

Hope it helps!

**Comment by yoko-** [comment]
Good Job Felipe. Thank You for all your hard work on this.
